plugins:
  - KinovaArmGen3

KinovaArmGen3:
  type: kinova_gen3_pad_plugin/KinovaArmGen3
  arm_control_topic_name: arm/in/cartesian_velocity
  arm_base_control_topic_name: arm/in/joint_velocity 
  arm_stop_motion_topic_name: arm/in/stop	
  gripper_command_service_name: arm/base/send_gripper_command
  robot_in_emergency_topic_name: robotnik_base_hw/emergency_stop
  trigger_emergency_topic_name: arm/in/emergency_stop
  clear_faults_topic_name: arm/in/clear_faults
  max_linear_speed: 1.0
  max_angular_speed: 2.0
  max_base_speed: 0.3
  config:
    button_deadman: 4
    button_movement_deadman: 5 # this plugin will not work if movement deadman button is pressed

    axis_linear_x_ee: 0
    axis_linear_y_ee: 1
    axis_linear_z_ee: 7

    axis_angular_x_ee: 4
    axis_angular_y_ee: 3
    axis_angular_z_ee: 6

    button_speed_up: 2
    button_speed_down: 0

    button_rotate_base_pos: 7
    button_rotate_base_neg: 6

    button_open_gripper: 1
    button_close_gripper: 3
